name: Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Clear and concise bug summary
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact commands and steps
      placeholder: |
        1. Run ...
        2. Call ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Rust, Node, ctx-agent version
      placeholder: |
        - OS:
        - rustc --version:
        - node --version:
        - ctx-agent --version:
    validations:
      required: true
